-- RNDM Chat v34
-- No manual SQL is required for the v34 admin UI package.
-- The privileged profile-field protection was applied to the connected Supabase project.
-- User profile/email editing is handled by the deployed `admin-user-manage` Edge Function.
-- Existing moderation RPCs keep server-side role checks and are only called after authentication.
