import {esc,icon,ib,avatar,time,day,preview,richText,safeURL,sid} from './core.js?v=47.0.0';
import {staffRole} from './admin.js?v=47.0.0';
import {defaultColors,validColors} from './theme.js?v=47.0.0';

export function shell(app) {
  const nav=[['random','Рулетка'],['chats','Чаты'],['contacts','Контакты'],['channels','Каналы'],['tapolka','Тапалка'],['stars','Звёзды'],['notifications','Уведомления'],['clips','Клипы'],['calls','Звонки'],['saved','Избранное'],['settings','Настройки'],...(staffRole(app.profile.app_role)?[['admin','Админка']]:[])];
  return `<div class="workspace" id="workspace">
    <aside class="rail" aria-label="Разделы"><span class="brand-mark" aria-label="RNDM Chat">R</span>
      <nav class="rail-nav">${nav.map(([name,label])=>`<button class="nav-item ${app.route===name?'active':''}" data-nav="${name}" type="button" title="${label}">${icon(name)}<span>${label}</span>${name==='notifications'?'<i class="notif-rail-badge" id="notifRailCount" hidden></i>':''}</button>`).join('')}</nav>
      <div class="rail-bottom">${ib('moon','Сменить тему','theme')}<button class="rail-me" data-nav="settings" aria-label="Мой профиль">${avatar(app.profile)}</button></div>
    </aside>
    <aside class="sidebar" aria-label="Список чатов">
      <div class="sidebar-header"><div class="sidebar-title"><h1 id="sectionTitle">Чаты</h1><span class="count-pill" id="sectionCount"></span>${staffRole(app.profile.app_role)?`<button class="icon-button mobile-admin-entry" data-nav="admin" type="button" aria-label="Открыть админку" title="Админка">${icon('shield')}</button>`:''}<button type="button" class="notification-top-button" data-nav="notifications" aria-label="Уведомления" title="Уведомления">${icon('bell')}<span id="notificationsHeaderCount" hidden></span></button><button type="button" class="star-wallet-quick" data-nav="stars" aria-label="Открыть кошелёк звёзд" title="Звёзды и подарки"><span>⭐</span><strong id="starBalanceNav">${Number(app.profile.stars||0).toLocaleString('ru-RU')}</strong></button>${ib('plus','Новый чат','new','new-chat')}</div>
        <label class="searchbox">${icon('search')}<input id="listSearch" placeholder="Поиск" aria-label="Поиск чатов и людей" autocomplete="off">${ib('close','Очистить поиск','clear-search','small')}</label>
      </div>
      <div class="stories-strip" id="storiesStrip" aria-label="Истории"></div>
      <div class="folder-tabs" id="folderTabs" aria-label="Фильтры чатов"></div>
      <div class="sidebar-list" id="dialogList"></div>
      <div class="sidebar-footer"><span class="status-dot" id="statusDot"></span><span id="connectionText">RNDM · на связи</span></div>
    </aside>
    <main class="pane" id="pane" aria-label="Переписка"></main>
  </div>`;
}
export function welcome() {
  return `<section class="welcome"><div class="welcome-logo">${icon('chats')}</div><span class="eyebrow">Твой круг. Твой ритм.</span><h2>Ближе, чем кажется.</h2><p>Выбери чат и продолжи разговор.<br>Всё важное — в одном месте.</p><button class="primary" data-action="new">${icon('plus')}Начать общение</button><button type="button" class="secondary welcome-random" data-nav="random">${icon('random')} Найти случайного собеседника</button><div class="welcome-tags"><span>${icon('lock')}Личные чаты</span><span>${icon('contacts')}Группы</span><span>${icon('channels')}Каналы</span></div></section>`;
}
export function randomSidebar() {
  return `<button type="button" class="random-sidebar-entry" data-nav="random"><span class="random-sidebar-orb">${icon('random')}</span><span><b>RNDM Рулетка</b><small>Новый собеседник в один клик</small></span><span class="random-sidebar-arrow">→</span></button>`;
}
export function randomPage({searching=false,filterLanguage='any',filterInterest='any',count=null,matched=null,person=null,error='',history=[]}) {
  const languages=[['any','Любой язык'],['ru','Русский'],['en','English']];
  const interests=[['any','Любая тема'],['games','🎮 Игры'],['music','🎵 Музыка'],['study','📚 Учёба'],['tech','💻 Технологии'],['movies','🎬 Кино'],['life','💬 Общение']];
  const options=(rows,value)=>rows.map(([id,label])=>`<option value="${id}" ${id===value?'selected':''}>${esc(label)}</option>`).join('');
  const result=matched?`<section class="random-found" role="status"><span class="random-status success">● СОВПАДЕНИЕ!</span><div class="random-found-person">${avatar(person||{display_name:'Собеседник'},'large')}<h3>${esc(person?.display_name||person?.username||'Собеседник найден')}</h3><p>${person?.username?'@'+esc(person.username):'Новый собеседник RNDM'}</p></div><p>Теперь вы можете познакомиться и начать разговор.</p><div class="random-found-actions"><button class="primary" data-action="random-open-chat">${icon('chats')} Открыть чат</button><button class="secondary" data-action="random-profile">Профиль</button><button class="secondary" data-action="random-friend">Добавить в друзья</button><button class="secondary" data-action="random-gift">🎁 Подарить</button><button class="secondary" data-action="random-next">${icon('random')} Другой человек</button></div></section>`:'';
  const waiting=searching?`<section class="random-wait" role="status"><div class="random-spinner">${icon('random')}</div><h3>Ищем собеседника…</h3><p>Как только другой участник начнёт поиск, мы создадим ваш чат.</p><button class="secondary" data-action="random-stop">Остановить поиск</button></section>`:'';
  const start=!searching&&!matched?`<section class="random-ready"><button class="random-start" data-action="random-start">${icon('random')} Начать поиск</button><p>Ты попадёшь в очередь только после нажатия. Можно выйти в любой момент.</p></section>`:'';
  return `<header class="chat-header">${ib('back','К чатам','back','back-mobile')}<div class="header-title"><h2>RNDM Рулетка</h2><p>Знакомства по интересам</p></div></header><div class="random-page">
    <div class="random-hero"><span class="eyebrow">ЗНАКОМЬСЯ ПО-НОВОМУ</span><div class="random-planet">${icon('random')}<i></i><i></i><i></i></div><h1>Никогда не знаешь,<br>кто встретится следующим.</h1><p>Находи новых людей для настоящего общения, без анкет и свайпов.</p></div>
    <div class="random-settings"><label>Язык собеседника<select id="randomLanguage" ${searching?'disabled':''}>${options(languages,filterLanguage)}</select></label><label>Общая тема<select id="randomInterest" ${searching?'disabled':''}>${options(interests,filterInterest)}</select></label><div class="random-counter">${icon('contacts')} <strong>${count===null?'—':Number(count)}</strong><small>в поиске сейчас</small></div></div>
    ${error?`<p class="random-error" role="alert">${esc(error)}</p>`:''}${result}${waiting}${start}
    <div class="random-safety">${icon('shield')}<p>Ты сам решаешь, когда общаться. Пользователи из блок-листа не будут подобраны. Для поиска нужны открытые личные сообщения и доступный профиль. Сейчас собеседники видят обычные профили — режим полной анонимности не включён.</p></div>
    <section class="random-history"><div class="random-history-head"><h2>🤝 История знакомств</h2><p>Сохранённые собеседники и твои предыдущие совпадения</p></div>${history.length?history.map(row=>`<div class="random-history-person">${avatar(row.person||{})}<span><b>${esc(row.person?.display_name||row.person?.username||'Пользователь')}</b><small>${new Date(row.last_met_at).toLocaleDateString('ru-RU')} · ${Number(row.matches||1)} встреч</small></span><button type="button" class="secondary" data-action="random-history-favorite" data-user="${esc(row.partner_id)}" data-favorite="${row.is_favorite?'1':'0'}" aria-label="${row.is_favorite?'Убрать из избранных':'В избранные'}">${row.is_favorite?'★':'☆'}</button>${row.conversation_id?`<button type="button" class="primary" data-action="random-history-chat" data-chat="${esc(row.conversation_id)}">Написать</button>`:''}</div>`).join(''):'<div class="random-history-empty">Здесь появятся люди, с которыми вы познакомились через рулетку.</div>'}</section>
  </div>`;
}
export function row(item,app) {
  const pref=app.prefs[item.id] || {}, draft=app.drafts['chat:'+item.id]?.body;
  const last=item.last ? (day(item.last)==='Сегодня' ? time(item.last) : new Date(item.last).toLocaleDateString('ru-RU',{day:'2-digit',month:'2-digit'})) : '';
  const title=item.title || item.display_name || item.name || 'Пользователь';
  return `<button type="button" class="chat-row ${app.active?.id===item.id?'active':''}" data-open="${esc(item.id)}" data-kind="${item.kind || 'direct'}" aria-label="${esc(title)}" aria-current="${app.active?.id===item.id?'true':'false'}">${avatar(item,'',item.kind==='group'?'contacts':item.kind==='channel'?'channels':'')}<span class="row-content"><span class="row-top"><span class="row-name">${esc(title)}</span><span class="row-time">${last}</span></span><span class="row-bottom"><span class="row-preview ${draft?'draft':''}">${esc(draft ? 'Черновик: '+draft : item.preview || '')}</span>${pref.is_pinned ? icon('pin','pin-tiny') : ''}${app.state.muted?.includes(item.id) ? icon('mute','pin-tiny') : ''}${item.unread ? `<span class="unread">${item.unread>99?'99+':item.unread}</span>` : ''}</span></span></button>`;
}
export function personRow(person,action='person') {
  return `<button class="chat-row" data-${action}="${esc(person.id)}" type="button">${avatar(person)}<span class="row-content"><span class="row-name">${esc(person.display_name || person.username)}</span><span class="row-bottom"><span class="row-preview">@${esc(person.username || 'user')}${person.bio?' · '+esc(person.bio):''}</span></span></span>${icon('chevron','pin-tiny')}</button>`;
}
export function conversation(app) {
  const active=app.active;
  let title,status,person;
  if (active.kind==='saved') { title='Избранное';status='Заметки и сохранённые сообщения';person={display_name:title}; }
  else if (active.kind==='channel') { title=active.title;status=active.count+' подписчиков';person=active; }
  else {
    person=app.info.profiles.find(p=>p.id!==app.user.id) || app.profile;
    title=active.kind==='group' ? app.info.conv.title || 'Группа' : person.display_name || person.username || 'Пользователь';
    const online=!person.hide_last_seen && Date.now()-new Date(person.last_seen).getTime()<150000;
    status=active.kind==='group' ? app.info.members.length+' участников' : person.hide_last_seen ? 'Последний визит скрыт' : online ? 'в сети' : person.last_seen ? 'был(а) '+day(person.last_seen).toLowerCase()+' в '+time(person.last_seen) : 'Личный чат';
  }
  const canSend=active.kind!=='channel' || active.owner_id===app.user.id;
  return `<header class="chat-header">${ib('back','К списку чатов','back','back-mobile')}${active.kind==='direct'?`<button type="button" class="chat-header-avatar" data-person="${esc(person.id)}" aria-label="Открыть профиль">${avatar(person)}</button>`:avatar(person,'',active.kind==='saved'?'saved':active.kind==='channel'?'channels':active.kind==='group'?'contacts':'')}<button type="button" class="header-title" ${active.kind==='direct'?`data-person="${esc(person.id)}" title="Открыть профиль"`:'data-action="info"'}><h2>${esc(title)}</h2><p id="presenceText">${esc(status)}</p></button><div class="header-tools">${active.kind==='direct'?ib('gift','Подарить подарок','chat-gift')+ib('phone','Аудиозвонок','call-audio')+ib('video','Видеозвонок','call-video'):''}${ib('search','Поиск в переписке','chat-search')}${active.kind!=='saved'?ib('info','Информация','info','desktop-tool'):''}${ib('more','Меню чата','chat-menu')}</div></header>
    <div id="pinnedBanner" class="pinned-banner" hidden></div>
    <div class="chat-search" id="chatSearch" hidden><input type="search" id="messageSearch" placeholder="Поиск по всей переписке" aria-label="Поиск сообщений">${ib('close','Закрыть поиск','close-chat-search')}</div><div class="search-results" id="messageSearchResults" hidden></div>
    <div class="messages" id="messages" role="log" aria-label="Сообщения"></div>${ib('down','К новым сообщениям','bottom','jump-bottom')}
    ${canSend ? `<div class="composer-wrap"><div class="compose-context" id="replyContext" hidden></div><div class="compose-context" id="fileContext" hidden></div><div class="typing-line" id="typingLine" role="status" aria-live="polite"></div><div class="send-error" id="sendError" role="alert"></div><form class="composer" id="composer">${ib('attach','Прикрепить файл','attach')}${ib('emoji','Эмодзи','emoji')}<textarea id="messageInput" placeholder="Напиши сообщение…" rows="1" maxlength="4000" aria-label="Сообщение"></textarea>${['direct','group'].includes(active.kind)?ib('calendar','Отложить сообщение','schedule-message'):''}${ib('mic','Записать голосовое','voice')}<button type="submit" class="send-button" id="sendButton" title="Отправить сообщение" aria-label="Отправить сообщение">${icon('send')}</button></form><input id="attachmentInput" type="file" hidden><div class="compose-hint">${app.state.enterSend!==false?'Enter — отправить · Shift + Enter — новая строка':'Отправка кнопкой · Enter — новая строка'}</div></div>` : `<div class="readonly-composer">${active.joined?'Ты подписан(а). Новые публикации появятся здесь.':'Подпишись на канал, чтобы добавить его в свой список.'}${!active.joined?'<br><button class="primary" data-action="join-channel">Подписаться</button>':''}</div>`}`;
}
export function attachment(message) {
  const url=safeURL(message.attachment_url); if (!url) return '';
  const type=message.attachment_type || '';
  if (type.startsWith('image/')) return `<div class="attachment"><a href="${esc(url)}" target="_blank" rel="noopener noreferrer"><img src="${esc(url)}" alt="${esc(message.attachment_name || 'Изображение')}" loading="lazy"></a></div>`;
  if (type.startsWith('video/')) return `<div class="attachment"><video controls playsinline preload="metadata" src="${esc(url)}" aria-label="${esc(message.attachment_name || 'Видео')}"></video></div>`;
  if (type.startsWith('audio/')) return `<div class="attachment"><audio controls preload="metadata" src="${esc(url)}" aria-label="${esc(message.attachment_name || 'Голосовое сообщение')}"></audio></div>`;
  return `<div class="attachment"><a class="file-card" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${icon('file')}<span>${esc(message.attachment_name || 'Файл')}</span>${icon('download')}</a></div>`;
}
export function messageHTML(message,app) {
  const own=message.sender_id===app.user.id || message.note;
  const person=app.info?.profiles?.find(p=>p.id===message.sender_id) || app.peopleMap[message.sender_id] || app.profile;
  const reply=app.replyLookup[sid(message.reply_to)] || app.messages.find(x=>sid(x.id)===sid(message.reply_to));
  const replies=message.reply_to ? `<button class="reply-preview" data-jump="${esc(message.reply_to)}"><b>Ответ ${reply ? esc(app.peopleMap[reply.sender_id]?.display_name || app.info?.profiles?.find(p=>p.id===reply.sender_id)?.display_name || 'на сообщение') : 'на сообщение'}</b><span>${reply ? esc(preview(reply)) : 'Сообщение #'+esc(message.reply_to)}</span></button>` : '';
  const rs=app.reactions.filter(r=>sid(r.message_id || r.post_id)===sid(message.id)), groups=new Map();
  for (const r of rs) { const g=groups.get(r.emoji) || {n:0,mine:false};g.n++;g.mine ||= r.user_id===app.user.id;groups.set(r.emoji,g); }
  const read=app.active.kind==='direct' && own && app.info?.members.filter(x=>x.user_id!==app.user.id).some(x=>x.last_read_at && new Date(x.last_read_at)>=new Date(message.created_at));
  return `${!own && app.active.kind==='group' ? avatar(person,'small') : ''}<div class="bubble">${!own && app.active.kind==='group' ? `<button class="message-sender" data-person="${esc(message.sender_id)}">${esc(person.display_name || person.username || 'Участник')}</button>` : ''}${message.deleted_at ? '<p class="message-body deleted">Сообщение удалено</p>' : `${message.forwarded_from ? '<div class="forwarded">Пересланное сообщение</div>' : ''}${replies}${message.body ? `<div class="message-body">${richText(message.body)}</div>` : ''}${attachment(message)}${groups.size ? `<div class="reaction-list">${[...groups].map(([emoji,g])=>`<button class="reaction-chip ${g.mine?'mine':''}" data-reaction="${esc(message.id)}" data-emoji="${esc(emoji)}">${esc(emoji)} <span>${g.n}</span></button>`).join('')}</div>` : ''}`}
    <div class="message-meta">${message.edited_at?'<span class="edited">изменено</span>':''}<span>${time(message.created_at)}</span>${own && app.active.kind!=='saved' && app.active.kind!=='channel' ? icon(read?'double':'check',read?'read':'') : ''}</div>
    ${app.active.kind==='channel' && !message.deleted_at ? `<button class="comment-link" data-comments="${esc(message.id)}">${icon('chats')}Комментарии${icon('chevron','pin-tiny')}</button>` : ''}</div><div class="message-actions">${message.deleted_at ? '' : `<button type="button" class="icon-button small" data-message-menu="${esc(message.id)}" title="Действия с сообщением" aria-label="Действия с сообщением">${icon('more')}</button>`}</div>`;
}
export function settings(app) {
  const p=app.profile,colors=validColors(app.state.colors)?app.state.colors:document.documentElement.dataset.theme==='light'?{accent:'#7953e5',background:'#f2f3fa',incoming:'#ffffff',outgoing:'#e4dafc'}:defaultColors;
  return `<header class="chat-header">${ib('back','К чатам','back','back-mobile')}<h2 style="font-size:16px">Мой RNDM</h2></header><section class="settings-pane"><h2>Настройки</h2>${staffRole(app.profile.app_role)?`<section class="settings-card"><h3>Управление сайтом</h3><div class="settings-body"><p class="muted">Пользователи, жалобы, публикации и журнал действий.</p><button class="primary" data-nav="admin">${icon('shield')}Открыть админку</button></div></section>`:''}
    <section class="settings-card"><h3>Профиль</h3><div class="settings-body"><button class="secondary" type="button" data-action="my-profile">Посмотреть мой профиль</button></div><form class="settings-body" id="profileForm"><div class="profile-edit">${avatar(p,'large')}<div><b>${esc(p.display_name)}</b><p>@${esc(p.username)}</p><button type="button" class="text-button" data-action="avatar">Изменить фото</button></div></div><input type="file" id="avatarInput" accept="image/jpeg,image/png,image/webp,image/gif" hidden><label class="field">Имя<input name="display_name" value="${esc(p.display_name)}" maxlength="60" required></label><label class="field">Имя пользователя<input name="username" value="${esc(p.username)}" pattern="[a-zA-Z0-9_]{3,32}" maxlength="32" required><small>От 3 до 32 символов: латинские буквы, цифры и _.</small></label><label class="field">О себе<textarea name="bio" rows="3" maxlength="500">${esc(p.bio)}</textarea></label><label class="field">Обложка профиля<div class="profile-cover-preview" ${p.cover_url?`style="background-image:url('${esc(p.cover_url)}')"`:''}></div><button type="button" class="secondary" data-action="cover">Загрузить обложку</button><input type="file" id="coverInput" accept="image/jpeg,image/png,image/webp" hidden></label><div id="profileError"></div><button class="primary" type="submit">Сохранить профиль</button></form></section>
    <section class="settings-card"><h3>⭐ Звёзды и подарки</h3><div class="settings-body"><div class="settings-wallet-shortcut"><div><span class="star-glow" aria-hidden="true">⭐</span><strong>${Number(p.stars||0).toLocaleString('ru-RU')} звёзд</strong><small>Баланс, ежедневный бонус и история подарков</small></div><button type="button" class="primary" data-nav="stars">Открыть кошелёк</button></div></div></section>
    ${profileAppearanceForm(p)}
    <section class="settings-card"><h3>♫ Музыка профиля</h3><form id="profileMusicForm" class="settings-body"><p class="muted">Добавь ссылку HTTPS на свой аудиофайл MP3/M4A/OGG. Музыка воспроизводится только по нажатию посетителя.</p><label class="field">Название трека<input name="music_title" maxlength="100" value="${esc(p.music_title||'')}" placeholder="Название"></label><label class="field">Ссылка на аудио<input name="profile_music_url" type="url" value="${esc(p.profile_music_url||'')}" placeholder="https://…/music.mp3" maxlength="2000"></label><div id="profileMusicError"></div><button type="submit" class="primary">Сохранить музыку</button></form><div class="settings-body"><button type="button" class="secondary" data-action="my-profile">Посмотреть публикации в профиле</button></div></section>
    <section class="settings-card"><h3>Оформление</h3><div class="settings-body"><div class="theme-options"><button class="theme-choice ${document.documentElement.dataset.theme!=='light'?'active':''}" data-set-theme="dark">${icon('moon')}Тёмная</button><button class="theme-choice ${document.documentElement.dataset.theme==='light'?'active':''}" data-set-theme="light">${icon('sun')}Светлая</button></div><form id="colorsForm" class="colors-form"><h4>Твои цвета</h4><p class="muted">Выбери любой оттенок. Изменения видны сразу; нажми «Сохранить цвета», чтобы оставить их.</p><div class="color-grid">${Object.entries({accent:'Кнопки и акценты',background:'Фон интерфейса',incoming:'Входящие сообщения',outgoing:'Твои сообщения'}).map(([key,label])=>`<label class="color-field"><span>${label}</span><span class="color-control"><input type="color" name="${key}" value="${colors[key]}" aria-label="${label}"><output>${colors[key].toUpperCase()}</output></span></label>`).join('')}</div><div class="palette-preview"><span class="preview-incoming">Привет! Как тебе эти цвета?</span><span class="preview-outgoing">Теперь RNDM выглядит по-моему ✨</span></div><div id="colorsError" role="alert"></div><div class="color-actions"><button class="primary" type="submit">Сохранить цвета</button><button class="secondary" type="button" data-action="reset-colors">Сбросить</button></div></form><p class="muted" style="font-size:11px;margin:20px 0 12px">Фон переписки</p><div class="theme-swatches">${['default','violet','mint','ocean','sunset'].map(t=>`<button class="theme-swatch ${t} ${app.state.wallpaper===t?'active':''}" data-wallpaper="${t}" aria-label="${{default:'Обычный',violet:'Фиолетовый',mint:'Мятный',ocean:'Океан',sunset:'Закат'}[t]}"></button>`).join('')}</div></div></section>
    <section class="settings-card"><h3>Общение и приватность</h3><label class="setting-row"><div>Отправка клавишей Enter<small>Shift + Enter добавляет новую строку.</small></div><input type="checkbox" data-setting="enterSend" ${app.state.enterSend!==false?'checked':''}></label><div class="setting-row"><div>Уведомления о сообщениях<small>Когда RNDM открыт в фоновой вкладке.</small></div>${window.Notification?`<button class="text-button" data-action="notifications">${app.state.notifications?'Выключить':'Включить'}</button>`:'<span class="muted" style="font-size:10px">Недоступны</span>'}</div><label class="setting-row"><div>Скрыть последний визит<small>Другие пользователи не увидят, когда ты был(а) в сети.</small></div><input type="checkbox" data-privacy="hide_last_seen" ${p.hide_last_seen?'checked':''}></label><label class="setting-row"><div>Разрешить личные сообщения всем<small>Для поиска собеседника в рулетке требуется разрешить сообщения всем.</small></div><input type="checkbox" data-privacy="allow_messages" ${p.allow_messages==='everyone'?'checked':''}></label><label class="setting-row"><div>Показываться в поиске<small>Нужен для чат-рулетки.</small></div><input type="checkbox" data-privacy="discoverable" ${p.discoverable?'checked':''}></label><label class="setting-row"><div>Закрытый профиль<small>Закрытые профили не участвуют в чат-рулетке.</small></div><input type="checkbox" data-privacy="profile_private" ${p.profile_private?'checked':''}></label></section>
    <section class="settings-card" id="languageSettings"><h3>🌐 Язык приложения / Language</h3><div class="settings-body"><label class="field">Язык интерфейса / Interface language<select id="appLanguage"><option value="ru" ${p.app_language!=='en'?'selected':''}>Русский</option><option value="en" ${p.app_language==='en'?'selected':''}>English</option></select></label><label class="field">Цензура<select id="censorshipMode"><option value="strict" ${p.censorship_mode==='strict'?'selected':''}>Строгая</option><option value="mask" ${p.censorship_mode!=='off'&&p.censorship_mode!=='strict'?'selected':''}>Маскировать мат</option><option value="off" ${p.censorship_mode==='off'?'selected':''}>Без маскировки</option></select></label><button type="button" class="primary" data-action="save-content-settings">Сохранить / Save</button></div></section>
    <section class="settings-card"><h3>🔔 Уведомления</h3><div class="settings-body"><button type="button" class="secondary" data-nav="notifications">Открыть центр уведомлений</button><label class="setting-row"><span>Звуковой сигнал при новых событиях<small>Только когда приложение открыто. Можно отключить.</small></span><input type="checkbox" data-setting="notificationSound" ${app.state.notificationSound?'checked':''}></label><button type="button" class="secondary" data-action="notifications-permission">Разрешить системные уведомления</button></div></section>
    <section class="settings-card"><h3>📞 Диагностика звонков</h3><div class="settings-body"><p class="muted">Проверь WebRTC, HTTPS, микрофон и наличие TURN для звонков между разными сетями.</p><button class="secondary" type="button" data-action="diagnose-calls">Проверить устройство</button></div></section>
    <section class="settings-card"><h3>Аккаунт</h3><div class="settings-body"><p class="muted" style="font-size:12px;overflow-wrap:anywhere;margin-bottom:16px">${esc(app.user.email)}</p><button class="secondary" data-action="password">Изменить пароль</button><button class="detail-action danger" data-action="logout" style="margin-top:13px">${icon('logout')}Выйти из аккаунта</button></div></section><p class="muted" style="font-size:10px;text-align:center">RNDM Chat · 47.0 · Общение в твоём ритме</p></section>`;
}
export function authView(mode, email='') {
  const labels={login:['С возвращением.','Войди в свой RNDM и продолжи разговор.'],register:['Твой новый круг.','Создай аккаунт и будь ближе к своим.'],forgot:['Восстановим доступ.','Отправим ссылку для смены пароля на твою почту.'],recovery:['Новый пароль.','Придумай новый пароль для своего аккаунта.']};
  const [title,sub]=labels[mode];
  return `<div class="auth-page"><section class="auth-intro"><div class="auth-brand"><span class="brand-mark">R</span>RNDM Chat</div><div class="auth-copy"><span class="eyebrow">Твой круг. Твой ритм.</span><h1>Разговоры,<br>которые<br><span>сближают.</span></h1><p>Личные сообщения, группы и каналы.<br>Место для своих — и для новых встреч.</p></div><p class="auth-footer">RNDM Chat · Общение без лишнего</p></section><section class="auth-form-wrap"><div class="auth-form-card"><div class="auth-mobile-brand"><span class="brand-mark">R</span>RNDM Chat</div><h2>${title}</h2><p>${sub}</p><form id="authForm" data-mode="${mode}">
    ${mode==='register'?'<label class="field">Как тебя зовут<input name="name" autocomplete="name" maxlength="60" required></label><label class="field">Имя пользователя<input name="username" placeholder="your_name" autocomplete="username" pattern="[a-zA-Z0-9_]{3,32}" minlength="3" maxlength="32" required><small>Латинские буквы, цифры и _. Минимум 3 символа.</small></label>':''}
    ${mode!=='recovery'?`<label class="field">Почта<input name="email" type="email" value="${esc(email)}" placeholder="you@example.com" autocomplete="email" required></label>`:''}
    ${mode!=='forgot'?`<label class="field">Пароль<input name="password" type="password" placeholder="${mode==='login'?'Твой пароль':'Не менее 8 символов'}" autocomplete="${mode==='login'?'current-password':'new-password'}" ${mode==='login'?'':'minlength="8"'} maxlength="128" required></label>`:''}
    ${mode==='recovery'?'<label class="field">Повтори пароль<input name="password2" type="password" autocomplete="new-password" minlength="8" required></label>':''}
    ${mode==='login'?'<button type="button" class="text-button" data-auth="forgot">Забыл(а) пароль?</button>':''}<div id="authMessage" role="alert"></div><button class="primary" type="submit">${{login:'Войти',register:'Создать аккаунт',forgot:'Отправить ссылку',recovery:'Сохранить пароль'}[mode]}${icon('chevron')}</button></form><div class="auth-switch">${mode==='login'?'Впервые здесь? <button data-auth="register">Создать аккаунт</button>':'<button data-auth="login">Назад ко входу</button>'}</div></div></section>${ib('moon','Сменить тему','theme','auth-theme')}</div>`;
}

export function tapolka(app,board=[],mine=0,catState={}) {
  const top=board.slice(0,20);
  return `<header class="chat-header">${ib('back','К чатам','back','back-mobile')}<div class="header-title"><h2>🐱 Котик · Тапалка</h2><p>Общий игровой канал RNDM</p></div><button class="secondary" data-action="tapolka-refresh">Обновить</button></header>
  <section class="tapolka-page">
    <div class="tapolka-hero"><span class="eyebrow">RNDM GAME CHANNEL</span><h1>Тапай. Набирай очки. Поднимайся в рейтинг.</h1><p>Твои нажатия сохраняются в облаке и синхронизируются между телефоном и ПК.</p><div class="tapolka-score"><small>Твой счёт</small><strong id="tapolkaMine">${Number(mine||0).toLocaleString('ru-RU')}</strong><span>тапов</span></div><button class="tapolka-button" id="tapolkaButton" data-action="tapolka-tap" aria-label="Тапнуть"><span class="tap-cat cat-skin-${esc(catState.skin_id||'classic')}" aria-hidden="true">${({classic:'🐱',ginger:'🐈',night:'🐈‍⬛',cosmic:'🐱'})[catState.skin_id]||'🐱'}<span class="cat-accessory cat-accessory-${esc(catState.accessory_id||'none')}">${({none:'',bow:'🎀',glasses:'🕶️',crown:'👑'})[catState.accessory_id]||''}</span></span><b>ПОГЛАДИТЬ</b><small>нажимай быстрее</small></button><div class="tapolka-pending" id="tapolkaPending"></div></div>
    ${catProgress(catState)}<div class="tapolka-board"><div class="tapolka-board-head"><div><span class="eyebrow">ТОП ИГРОКОВ</span><h2>Рейтинг канала</h2><div class="cat-leader-tabs"><button type="button" class="active" data-action="cat-board-mode" data-mode="all">За всё время</button><button type="button" data-action="cat-board-mode" data-mode="weekly">За неделю</button></div></div><button class="icon-button" data-action="tapolka-refresh" aria-label="Обновить рейтинг">${icon('refresh')}</button></div><div id="tapolkaBoard">${top.map((x,i)=>`<div class="tapolka-rank ${x.user_id===app.user.id?'mine':''}"><span class="tapolka-place">${i+1}</span>${avatar(x)}<span class="row-content"><b>${esc(x.display_name||x.username||'Игрок')}</b><small>@${esc(x.username||'user')}</small></span><strong>${Number(x.taps||0).toLocaleString('ru-RU')}</strong></div>`).join('')||'<div class="sidebar-empty"><p>Стань первым игроком — сделай первый тап.</p></div>'}</div></div>
  </section>`;
}

const PROFILE_COVERS=['aurora','cosmos','sunset','ocean','forest','rose','minimal'];
const PROFILE_FRAMES=['none','neon','gold','frost','rose','rainbow'];
export function profileAppearanceForm(p) {
 const style=PROFILE_COVERS.includes(p.profile_cover_style)?p.profile_cover_style:'aurora';
 const frame=PROFILE_FRAMES.includes(p.frame_id)?p.frame_id:'none';
 const accent=/^#[0-9a-f]{6}$/i.test(p.profile_accent||'')?p.profile_accent:'#9478ff';
 const styles=[['aurora','Аврора'],['cosmos','Космос'],['sunset','Закат'],['ocean','Океан'],['forest','Лес'],['rose','Роза'],['minimal','Минимализм']];
 const frames=[['none','Без рамки'],['neon','Неон'],['gold','Золото'],['frost','Лёд'],['rose','Розовая'],['rainbow','Радуга']];
 const options=(rows,v)=>rows.map(([id,label])=>`<option value="${id}" ${v===id?'selected':''}>${label}</option>`).join('');
 return `<section class="settings-card profile-decor-editor"><h3>✨ Оформление профиля</h3><div class="settings-body"><p class="muted">Эти украшения увидят друзья, когда откроют твой профиль. Настройки хранятся в базе.</p><form id="profileStyleForm">
 <div class="profile-live-preview" id="profileLivePreview" style="--profile-accent:${accent}"><div class="profile-live-cover cover-${style}" id="profileLiveCover"></div><div class="profile-live-avatar"><span id="profileLiveFrame" class="avatar-frame frame-${frame}">${avatar(p,'large')}</span><div><b>${esc(p.display_name)}</b><small>@${esc(p.username)}</small></div></div></div>
 <label class="field">Фон профиля<select name="profile_cover_style" id="profileCoverStyle">${options(styles,style)}</select></label>
 <label class="field">Рамка аватара<select name="frame_id" id="profileFrame">${options(frames,frame)}</select></label>
 <label class="field">Порядок блоков профиля<select name="profile_layout"><option value="gifts-first" ${p.profile_layout!=='posts-first'?'selected':''}>Сначала подарки</option><option value="posts-first" ${p.profile_layout==='posts-first'?'selected':''}>Сначала публикации</option></select></label>
 <label class="field">Цвет профиля<span class="profile-accent-input"><input type="color" name="profile_accent" id="profileAccent" value="${accent}"><output id="profileAccentText">${accent.toUpperCase()}</output></span></label>
 <div id="profileStyleError" role="alert"></div><button type="submit" class="primary">Сохранить оформление</button></form></div></section>`;
}
export function publicProfileView(app,p,gifts=[],moments=[],social={}) {
  if(!p)return `<div class="empty-state"><h2>Профиль не найден</h2></div>`;
  const rawCover=p.cover_url&&safeURL(p.cover_url);
  const cover=rawCover?`style="background-image:url('${esc(rawCover)}')"`:'';
  const coverStyle=PROFILE_COVERS.includes(p.profile_cover_style)?p.profile_cover_style:'aurora';
  const frame=PROFILE_FRAMES.includes(p.frame_id)?p.frame_id:'none';
  const accent=/^#[0-9a-f]{6}$/i.test(p.profile_accent||'')?p.profile_accent:'#9478ff';
  const mine=p.id===app.user.id;
  const badges=[...(p.is_verified?['✅ Проверенный']:[]),...(p.is_premium?['💎 Premium']:[]),...(Number(p.xp)>=1000?['🏅 Опытный']:[]),...(gifts.length>=5?['🎁 Коллекционер']:[])];
  const role=p.app_role&&p.app_role!=='user'?`<span class="profile-role">${esc(p.app_role)}</span>`:'';
  return `<div class="public-profile styled-profile" style="--profile-accent:${accent}">
    <header class="profile-cover cover-${coverStyle}" ${cover}>${ib('back','Назад','profile-back','profile-back')}<div class="profile-cover-shade"></div></header>
    <section class="profile-main-card">
      <div class="profile-big-avatar"><span class="avatar-frame frame-${frame}">${avatar(p)}</span></div>
      <div class="profile-identity"><h1>${esc(p.display_name||p.username||'Пользователь')} ${p.is_verified?'✓':''}</h1><p>@${esc(p.username||'user')} ${role}</p></div>
      <div class="profile-actions">${mine?`<button class="primary" data-nav="settings">Редактировать и оформить профиль</button><button class="secondary" data-nav="stars">⭐ Мой кошелёк</button>`:`<button class="primary" data-action="profile-message" data-user="${esc(p.id)}">Написать</button><button class="secondary" data-action="profile-friend" data-user="${esc(p.id)}">Добавить</button><button class="secondary" data-action="profile-gift" data-user="${esc(p.id)}">🎁 Подарить</button><button class="secondary" data-action="profile-follow" data-user="${esc(p.id)}" data-following="${social.following?'1':'0'}">${social.following?'✓ Подписан':'+ Подписаться'}</button>`}</div>
      <p class="profile-bio">${esc(p.bio||'Пользователь пока ничего о себе не рассказал.')}</p>
      ${p.profile_music_url&&safeURL(p.profile_music_url)?`<div class="profile-audio"><b>♫ ${esc(p.music_title||'Музыка профиля')}</b><audio controls preload="none" src="${esc(safeURL(p.profile_music_url))}"></audio></div>`:''}
      <div class="profile-stats"><span><b>${Number(p.reputation||0)}</b>репутация</span><span><b>${Number(p.xp||0)}</b>XP</span><span><b>${Number(p.stars||0)}</b>звёзд</span><span><b>${Number(social.followers||0)}</b>подписчиков</span></div>${badges.length?`<div class="profile-badges">${badges.map(b=>`<span>${esc(b)}</span>`).join('')}</div>`:''}
      ${(()=>{const giftBlock=`<section class="gift-showcase"><h3>🎁 Коллекция подарков</h3><div class="gift-showcase-list">${gifts.length?gifts.map(g=>`<div class="gift-chip" title="${esc(g.gift_name)} от ${esc(g.sender_name)}"><span>${esc(g.gift_emoji)}</span><small>${esc(g.sender_name)}</small></div>`).join(''):'<p>Подарков пока нет</p>'}</div></section>`;const postsBlock=profileMoments(moments,mine);return p.profile_layout==='posts-first'?postsBlock+giftBlock:giftBlock+postsBlock})()}
      <div class="profile-details"><div><small>Статус</small><b>${esc(p.status||'offline')}</b></div><div><small>В RNDM с</small><b>${p.created_at?new Date(p.created_at).toLocaleDateString(app.profile?.app_language==='en'?'en-GB':'ru-RU'):'—'}</b></div></div>
    </section>
  </div>`;
}

export function giftShop(target,items,balance,personName='другу',lang='ru') {
  const t=(ru,english)=>lang==='en'?english:ru;
  const fmt=x=>Number(x||0).toLocaleString('ru-RU');
  const cards=items.map((g,i)=>`<label class="gift-picker-card ${Number(g.price)>Number(balance)?'unaffordable':''} ${Number(g.price)>=500?'rare':Number(g.price)>=100?'special':'common'}"><input type="radio" name="giftPick" value="${esc(g.id)}" data-price="${Number(g.price)}" ${i===0?'checked':''}><span class="gift-picker-emoji" aria-hidden="true">${esc(g.emoji)}</span><b>${esc(g.name)}</b>${g.rarity&&g.rarity!=='common'?`<small class="gift-rarity">${esc({rare:'Редкий',epic:'Эпический',legendary:'Легендарный'}[g.rarity]||g.rarity)}</small>`:''}<span class="gift-price">⭐ ${fmt(g.price)}</span></label>`).join('');
  return `<div class="gift-shop-v43" data-recipient="${esc(target)}"><div class="gift-to">${t('Отправить подарок','Send a gift to')} <b>${esc(personName)}</b></div><div class="gift-available"><span>${t('Твой баланс','Your balance')}</span><strong>⭐ ${fmt(balance)}</strong><button type="button" class="text-button" data-action="gift-wallet">${t('Кошелёк','Wallet')}</button></div><div class="gift-picker-grid" role="radiogroup" aria-label="${t('Выбрать подарок','Choose a gift')}">${cards||`<p class="muted">${t('Каталог пока недоступен','Catalog is unavailable')}</p>`}</div><label class="field">${t('Пожелание (необязательно)','Message (optional)')}<input id="giftNote" maxlength="160" placeholder="${t('Добавь несколько тёплых слов','Add a few kind words')}"></label><p class="gift-payment-hint">${t('Звёзды спишутся только после подтверждения. Получатель увидит подарок в профиле.','Stars will be deducted only after confirmation. The recipient will see your gift in their profile.')}</p><div class="gift-confirm-actions"><button type="button" class="secondary" data-action="gift-close">${t('Отмена','Cancel')}</button><button type="button" class="primary" data-action="gift-confirm" ${!items.length?'disabled':''}>🎁 ${t('Отправить подарок','Send gift')}</button></div></div>`;
}

/** Wallet with daily reward and durable incoming/outgoing gift timeline. */
export function starsWallet(app,{wallet={},history=[],friends=[],catalog=[]}={}) {
  const en=app.profile?.app_language==='en';
  const t=(ru,english)=>en?english:ru;
  const fmt=x=>Number(x||0).toLocaleString('ru-RU');
  const reward=wallet.claimed_today
    ?`<div class="star-reward-done">✓ ${t('Сегодня награда получена. Возвращайся завтра!','Reward collected today. Come back tomorrow!')}</div>`
    :`<button class="star-reward-button" type="button" data-action="stars-claim">${t('Получить ежедневные','Collect daily')} ⭐ 15 <span>+ 40 XP</span></button>`;
  const accepted=friends.filter(f=>f.status==='accepted'&&f.person).slice(0,12);
  const people=accepted.map(f=>`<button type="button" class="star-friend" data-action="stars-gift-to" data-user="${esc(f.person.id)}" title="Подарить ${esc(f.person.display_name)}">${avatar(f.person,'small')}<span>${esc(f.person.display_name||f.person.username)}</span><span>🎁</span></button>`).join('');
  const lines=history.map(g=>`<article class="star-history-row"><span class="star-history-emoji" aria-hidden="true">${esc(g.gift_emoji)}</span><div class="star-history-copy"><b>${esc(g.gift_name)}</b><button type="button" class="text-button" data-person="${esc(g.other_id)}">${g.direction==='sent'?t('Кому: ','To: '):t('От: ','From: ')}${esc(g.other_name||g.other_username||'Пользователь')}</button>${g.message?`<small class="star-history-note">${esc(g.message)}</small>`:''}<small>${new Date(g.created_at).toLocaleDateString(en?'en-GB':'ru-RU',{day:'numeric',month:'short',year:'numeric'})}</small></div><strong class="${g.direction==='sent'?'star-out':'star-in'}">${g.direction==='sent'?'−':'🎁'} ${fmt(g.price_paid)} ⭐</strong></article>`).join('');
  return `<header class="chat-header">${ib('back','К чатам','back','back-mobile')}<div class="header-title"><h2>⭐ ${t('Звёзды и подарки','Stars & Gifts')}</h2><p>${t('Твой кошелёк RNDM','Your RNDM wallet')}</p></div>${ib('refresh','Обновить баланс','stars-refresh')}</header>
  <div class="star-wallet-page"><section class="star-wallet-hero"><div class="star-wallet-orbit" aria-hidden="true"><img src="star-gold.webp" alt="" width="170" height="170"></div><span class="eyebrow">${t('ТВОЙ БАЛАНС','YOUR BALANCE')}</span><strong class="star-wallet-amount">${fmt(wallet.balance)}</strong><p>${t('Звёзды для подарков и приятных сюрпризов','Stars for gifts and fun surprises')}</p><div class="star-wallet-pills"><span>🎁 ${t('Получено:','Received:')} ${fmt(wallet.received)}</span><span>🎀 ${t('Отправлено:','Sent:')} ${fmt(wallet.sent)}</span><span>✨ XP: ${fmt(wallet.xp)}</span></div></section>
  <section class="star-wallet-section"><div class="star-wallet-section-title"><div><h3>${t('Ежедневная награда','Daily reward')}</h3><p>${t('Забирай бонус раз в день, без покупок','Claim once per day, no purchases')}</p></div><span class="star-bonus-emoji" aria-hidden="true"><img src="gift-gold.webp" alt="" width="92" height="92"></span></div>${reward}<small class="star-wallet-disclaimer">${t('Игровые звёзды RNDM. Они не являются денежными средствами и не обмениваются на деньги.','RNDM stars are in-app points, not money, and cannot be exchanged for cash.')}</small></section>
  <section class="star-wallet-section"><div class="star-wallet-section-title"><div><h3>${t('Подарить другу','Gift a friend')}</h3><p>${t('Выбери получателя или найди его по @username','Choose a friend or find a @username')}</p></div><span aria-hidden="true">💝</span></div><div class="star-friend-list">${people}</div><button class="secondary star-find-button" type="button" data-action="stars-find-user">${icon('search')} ${t('Найти получателя','Find recipient')}</button></section>
  <section class="star-wallet-section"><div class="star-wallet-section-title"><div><h3>${t('Коллекция подарков','Gift collection')}</h3><p>${t('Выбирай подарок по своему балансу','Choose a gift for your balance')}</p></div><span aria-hidden="true">✨</span></div><div class="star-catalog-preview">${catalog.map(g=>`<div class="star-catalog-gift rarity-${esc(g.rarity||'common')}"><span>${esc(g.emoji)}</span><b>${esc(g.name)}</b><small>⭐ ${fmt(g.price)}</small>${g.rarity==='legendary'?'<em>✦ Легендарный</em>':''}</div>`).join('')}</div><button type="button" class="secondary" data-action="stars-find-user">🎁 ${t('Отправить подарок','Send a gift')}</button></section>
  <section class="star-wallet-section"><div class="star-wallet-section-title"><div><h3>${t('История подарков','Gift history')}</h3><p>${t('Всё сохраняется в твоём аккаунте','Synced with your account')}</p></div><span aria-hidden="true">📜</span></div><div class="star-history">${lines||`<div class="star-empty"><span>🎁</span><p>${t('Пока нет подарков. Отправь первый другу!','No gifts yet. Send one to a friend!')}</p></div>`}</div></section></div>`;
}
export function giftRecipientRows(people=[],lang='ru') {
  const t=(ru,english)=>lang==='en'?english:ru;
  return people.length?people.map(p=>`<button type="button" class="gift-recipient-row" data-action="stars-gift-to" data-user="${esc(p.id)}">${avatar(p,'small')}<span>${esc(p.display_name||p.username)}<small>@${esc(p.username)}</small></span><span aria-hidden="true">🎁</span></button>`).join(''):`<p class="muted">${t('Никого не найдено.','No users found.')}</p>`;
}
export function giftRecipients(people=[],lang='ru') {
  const t=(ru,english)=>lang==='en'?english:ru;
  return `<div class="gift-recipients"><p class="muted">${t('Найди пользователя по имени или @username и отправь ему подарок.','Find someone by name or @username to send a gift.')}</p><label class="field">${t('Поиск','Search')}<input id="giftRecipientSearch" autocomplete="off" placeholder="${t('Введите имя или @username','Enter a name or @username')}" minlength="2"></label><div id="giftRecipientResults">${people.length?giftRecipientRows(people,lang):`<p class="muted">${t('Начни вводить имя или ник.','Start typing a name or username.')}</p>`}</div></div>`;
}


/** A daily-limited cat game with visible energy and server-owned upgrades. */
export function catProgress(state={}) {
 const energy=Number(state.energy??100),max=Number(state.max_energy??100);
 const percent=Math.max(0,Math.min(100,Math.round(100*energy/Math.max(1,max))));
 const today=Number(state.daily_taps||0),earned=Number(state.stars_earned_today||0);
 const limit=Number(state.energy_level||1),regen=Number(state.regen_level||1);
 return `<section class="cat-progression" aria-label="Прокачка котика">
  <div class="cat-energy-label"><b>⚡ Энергия <span id="catEnergyText">${energy} / ${max}</span></b><small>Восстановление: ${regen} за 8 сек.</small></div>
  <div class="cat-energy-track"><div id="catEnergyBar" style="width:${percent}%"></div></div>
  <div class="cat-progress-stats"><span>🏅 Уровень <b id="catLevel">${Number(state.level||1)}</b></span><span>⭐ Сегодня <b id="catStarsEarned">${earned} / 24</b></span><span>🐾 Сегодня <b id="catDailyTaps">${today}</b></span></div>
  <div class="cat-task-list"><h3>Задания на сегодня</h3>
   ${[[25,4],[75,8],[150,12]].map(([target,reward])=>`<div class="cat-task"><span>${today>=target?'✅':'⭐'} ${target} поглаживаний</span><b>${today>=target?'Получено':`+${reward} ⭐`}</b></div>`).join('')}</div>
  <div class="cat-cosmetics"><h3>🐾 Коллекция котиков</h3><p>Получай новые облики и аксессуары за уровни — без покупки за звёзды.</p><div class="cat-cosmetic-grid">${[['classic','🐱','Обычный',1],['ginger','🐈','Рыжий',1],['night','🐈‍⬛','Ночной',3],['cosmic','🌌','Космос',8]].map(([id,emoji,label,unlock])=>`<button type="button" class="cat-cosmetic-choice ${state.skin_id===id?'active':''}" data-action="cat-cosmetic" data-kind="skin" data-choice="${id}" ${Number(state.level||1)<unlock?'disabled':''}><span>${emoji}</span><b>${label}</b><small>${Number(state.level||1)<unlock?'Уровень '+unlock:state.skin_id===id?'Выбран':'Выбрать'}</small></button>`).join('')}</div><h4>Аксессуары</h4><div class="cat-cosmetic-grid">${[['none','✨','Без аксессуара',1],['bow','🎀','Бантик',2],['glasses','🕶️','Очки',4],['crown','👑','Корона',8]].map(([id,emoji,label,unlock])=>`<button type="button" class="cat-cosmetic-choice ${state.accessory_id===id?'active':''}" data-action="cat-cosmetic" data-kind="accessory" data-choice="${id}" ${Number(state.level||1)<unlock?'disabled':''}><span>${emoji}</span><b>${label}</b><small>${Number(state.level||1)<unlock?'Уровень '+unlock:state.accessory_id===id?'Выбран':'Выбрать'}</small></button>`).join('')}</div></div><div class="cat-upgrades"><h3>Улучшения котика</h3>
   <button type="button" class="cat-upgrade" data-action="cat-upgrade" data-upgrade="energy" ${limit>=5?'disabled':''}><span>⚡ Вместимость энергии <small>Уровень ${limit}/5 · +25 энергии</small></span><b>${limit>=5?'Максимум':'⭐ '+(30+20*(limit-1))}</b></button>
   <button type="button" class="cat-upgrade" data-action="cat-upgrade" data-upgrade="regen" ${regen>=5?'disabled':''}><span>💫 Восстановление <small>Уровень ${regen}/5 · быстрее восстанавливается</small></span><b>${regen>=5?'Максимум':'⭐ '+(45+25*(regen-1))}</b></button>
  </div><p class="cat-caution">Звёзды за задания начисляются сервером. Для честного рейтинга действуют лимиты энергии и скорости нажатий.</p>
 </section>`;
}

export function profileMoments(moments=[],mine=false) {
 const rows=moments.map(m=>`<article class="profile-post" data-post-id="${esc(m.id)}"><div class="profile-post-meta"><b>${m.is_featured?'📌 Закреплено':'✦ Публикация'}</b><small>${new Date(m.created_at).toLocaleDateString('ru-RU',{day:'2-digit',month:'short',year:'numeric'})}</small></div><p>${esc(m.body)}</p>${m.media_url&&safeURL(m.media_url)?`<a href="${esc(safeURL(m.media_url))}" target="_blank" rel="noopener noreferrer">Открыть вложение</a>`:''}${mine?`<div class="profile-post-actions">${!m.is_featured?`<button type="button" class="secondary" data-action="profile-post-pin" data-post="${esc(m.id)}">Закрепить</button>`:''}<button type="button" class="secondary danger" data-action="profile-post-delete" data-post="${esc(m.id)}">Удалить</button></div>`:''}</article>`).join('');
 return `<section class="profile-posts"><div class="profile-posts-header"><h3>Публикации</h3>${mine?'<button type="button" class="secondary" data-action="profile-post-new">+ Написать</button>':''}</div>${rows||'<p class="muted">Публикаций пока нет.</p>'}</section>`;
}


export function notificationsPage(app,rows=[],filter='all'){
 const en=app.profile?.app_language==='en';const t=(ru,english)=>en?english:ru;
 const tabs=[['all',t('Все','All')],['message',t('Сообщения','Messages')],['gift',t('Подарки','Gifts')],['friend',t('Друзья','Friends')]];
 const filtered=rows.filter(n=>filter==='all'||(filter==='friend'&&/friend|follow/i.test(n.kind))||(filter==='message'&&/message|mention/i.test(n.kind))||(filter==='gift'&&/gift|star/i.test(n.kind)));
 const iconFor=n=>/gift|star/i.test(n.kind)?'🎁':/friend|follow/i.test(n.kind)?'🤝':/call/i.test(n.kind)?'📞':/message/i.test(n.kind)?'💬':'🔔';
 return `<header class="chat-header">${ib('back','Назад','back','back-mobile')}<div class="header-title"><h2>🔔 ${t('Уведомления','Notifications')}</h2><p>${rows.filter(n=>!n.is_read).length} ${t('непрочитанных','unread')}</p></div><button type="button" class="secondary" data-action="notifications-all" ${rows.every(n=>n.is_read)?'disabled':''}>${t('Прочитать всё','Mark all read')}</button></header>
 <section class="notification-page"><div class="notif-tabs">${tabs.map(([id,label])=>`<button type="button" data-action="notifications-filter" data-filter="${id}" class="${filter===id?'active':''}">${label}</button>`).join('')}</div><div class="notif-list">
 ${filtered.map(n=>`<button type="button" class="notif-row ${n.is_read?'':'unread'}" data-action="notifications-open" data-id="${Number(n.id)}"><span class="notif-emoji">${iconFor(n)}</span><span class="notif-copy"><b>${esc(n.title)}</b><span>${esc(n.body)}</span><small>${new Date(n.created_at).toLocaleString(en?'en-GB':'ru-RU',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</small></span>${n.is_read?'':'<i class="notif-dot"></i>'}</button>`).join('')||`<div class="notif-empty">🔔 <p>${t('Здесь пока нет уведомлений.','No notifications here yet.')}</p></div>`}</div><p class="notif-footnote">${t('Сообщения и подарки сохраняются в Supabase. Уведомления вне приложения требуют отдельной настройки push-подписки.','Messages and gifts are saved in Supabase. Offline push needs a separate push subscription setup.')}</p></section>`;
}

